version: "3"
services:
  nextjs:
    build: ./docker/
    container_name: nextjs_container
    ports:
      - "3030:3000"
    tty: true
    volumes:
      - ./Front:/local/src
    environment:
      - CHOKIDAR_USEPOLLING=true